services:
  kafka-1:
    image: apache/kafka:3.7.0
    container_name: kafka-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093

  redpanda_console:
      image: redpandadata/console:v2.8.0
      container_name: redpanda_console 
      restart: always
      ports:
        - 8080:8080
      environment:
        - KAFKA_BROKERS=kafka-1:9092
      depends_on:
        - kafka-1