global:
  scrape_interval:     15s 
  evaluation_interval: 20s 
  scrape_timeout: 10s

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Discover Lag Explorer services to scrape.
  - job_name: "lag_explorer"
    static_configs:
      - targets: ["lag_explorer:8000"]
    