version: '3'

services:

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    platform: linux/amd64
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    platform: linux/amd64
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181/local
      - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka:9092
      - KAFKA_LISTENERS=plaintext://:9092

  burrow:
    image: burrow_burrow:latest
    container_name: burrow
    platform: linux/amd64
    volumes:
      - ./burrow.toml:/etc/burrow/burrow.toml
    ports:
      - 8000:8000
    depends_on:
      - kafka
    restart: always

  burrowui:
    image: generalmills/burrowui:latest
    container_name: burrow-stats
    platform: linux/amd64
    environment:
      - BURROW_HOME=http://burrow:8000/v3/kafka
    ports:
      - 3000:3000
    depends_on:
      - burrow
    restart: always
