version: '3'

services:

  zookeeper:
    image: zookeeper:3.7.0
    restart: always
    container_name: zookeeper
      
  kafka_1:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka_1
    restart: always
    environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENERS=plaintext://:9092
       - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka_1:9092
       - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka_1 -Dcom.sun.management.jmxremote.rmi.port=1099
    depends_on:
      - zookeeper
  kafka_2:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka_2
    restart: always
    environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENERS=plaintext://:9092
       - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka_2:9092
       - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka_2 -Dcom.sun.management.jmxremote.rmi.port=1099
    depends_on:
      - zookeeper
  kafka_3:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka_3
    restart: always
    environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENERS=plaintext://:9092
       - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka_3:9092
       - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka_3 -Dcom.sun.management.jmxremote.rmi.port=1099
    depends_on:
      - zookeeper

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    restart: always
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka_3:9092
      - KAFKA_CLUSTERS_0_JMXPORT=1099
      - KAFKA_CLUSTERS_0_JMXSSL=false
      - KAFKA_CLUSTERS_0_JMXUSERNAME=
      - KAFKA_CLUSTERS_0_JMXPASSWORD=
    depends_on:
      - kafka_1
      - kafka_2
      - kafka_3