version: '3'

services:

  burrow:
    image: burrow_burrow:latest
    container_name: burrow
    volumes:
      - ./burrow.toml:/etc/burrow/burrow.toml
    ports:
      - 8000:8000
    restart: always

  burrow-dashboard:
    image: joway/burrow-dashboard:latest
    container_name: dashboard
    ports: 
      - 8080:80
    environment:  
      - BURROW_BACKEND=http://burrow:8000
    depends_on:
      - burrow
    restart: always

networks:
  default:
    external:
      name: test-burrow