version: '3'

services:

  burrow:
    image: burrow_burrow:latest
    container_name: burrow
    volumes:
      - ./burrow.toml:/etc/burrow/burrow.toml
    ports:
      - 8000:8000
    depends_on:
      - zookeeper
      - kafka
    restart: always

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181/local
      - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka:9092
      - KAFKA_LISTENERS=plaintext://:9092

  burrow-dashboard:
    image: joway/burrow-dashboard:latest
    container_name: dashboard
    ports: 
      - 8080:80
    environment:  
      - BURROW_BACKEND=http://burrow:8000
    depends_on:
      - burrow
    restart: always