version: "3"
services:
  burrow:
    image: burrow_burrow:latest
    volumes:
      - ./burrow.toml:/etc/burrow/burrow.toml
    ports:
      - 8000:8000
    depends_on:
      - zookeeper
      - kafka
    restart: always

  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - 2181:2181
    restart: always



  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/local
      KAFKA_ADVERTISED_LISTENERS: plaintext://kafka:9092
      KAFKA_LISTENERS: plaintext://:9092