version: '3'

services:

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181/local
      - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka:9092
      - KAFKA_LISTENERS=plaintext://:9092

networks:
  default:
    external:
      name: test-burrow