version: '3'

services:

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    platform: linux/amd64
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    platform: linux/amd64
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181/local
      - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka:9092
      - KAFKA_LISTENERS=plaintext://:9092

  burrow:
    image: burrow_burrow:latest
    container_name: burrow
    platform: linux/amd64
    volumes:
      - ./burrow.toml:/etc/burrow/burrow.toml
    ports:
      - 8000:8000
    depends_on:
      - kafka
    restart: always

  burrow-stats:
    image: tulios/burrow-stats:latest
    container_name: burrow-stats
    platform: linux/amd64
    environment:
      - PORT=8022
    volumes:
      - ./configs.json:/opt/burrow-stats/configs.json
    ports:
      - 8022:8022
    depends_on:
      - burrow
    restart: always
