version: '3'

services:

  zookeeper:
    image: zookeeper:3.7.0
    restart: always
    container_name: zookeeper
    ports:
      - 2181:2181
      
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    restart: always
    environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENERS=plaintext://:9092
       - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka:9092
       - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099
       - JMX_PORT=1099
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  lag_explorer:
    image: seglo/kafka-lag-exporter:0.7.0
    container_name: lag_explorer
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/opt/docker/conf
    command: /opt/docker/bin/kafka-lag-exporter -Dconfig.file=/opt/docker/conf/application.conf -Dlogback.configurationFile=/opt/docker/conf/logback.xml
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - lag_explorer

  grafana:
    image: grafana/grafana:9.1.1
    container_name: grafana
    restart: always
    volumes:
      - ./prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
    ports:
      - 3000:3000
    depends_on:
      - prometheus