spring:
  application:
    name: management
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
      bindings:
        messageProducer-out-0:
          destination: "message.topic"
        messageConsumer-in-0:
          destination: "message.topic"
          group: "message-topic-consumer"
    function:
      definition: "messageConsumer"