version: '3'

services:

  zookeeper:
    image: zookeeper:3.7.0
    restart: always
    container_name: zookeeper
    platform: linux/amd64
    ports:
      - 2181:2181
      
  kafka_1:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka_1
    platform: linux/amd64
    restart: always
    environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENERS=plaintext://:9092
       - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka_1:9092
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafka_2:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka_2
    platform: linux/amd64
    restart: always
    environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENERS=plaintext://:9093
       - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka_2:9093
    ports:
      - 9093:9093
    depends_on:
      - zookeeper

  kafka_3:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka_3
    platform: linux/amd64
    restart: always
    environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENERS=plaintext://:9094
       - KAFKA_ADVERTISED_LISTENERS=plaintext://kafka_3:9094
    ports:
      - 9094:9094
    depends_on:
      - zookeeper