spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: tx-
      properties:
        enable.idempotence: true
    consumer:
      group-id: datx-consumer-group-1
      enable-auto-commit: false
      isolation-level: read_committed
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect